### ISSUE TITLE
Can you increase the gen_id? Thank you so much:)

### ISSUE THREAD

**Issue by rui40000** [natto-maki/ComfyUI-NegiTools#1]
Drawing in chatgpt can generate gen_id, which is very useful for modifying the picture. I don’t know if the relevant parameters of gen_id can be added to the API. That would be great if you could. Thank you very much for your work, I've been using it for the past few days。
 =*0*=

**Comment by natto-maki** [comment]
Thank you for your feedback.  Unfortunately, the API version of DALL-E3 does not seem to expose parameters that control or output random numbers such as gen_id or seed, etc. Therefore, it does not seem possible to reproduce or fine-tune an image once it has been output; let's pray together that OpenAI will provide these capabilities!

**Comment by natto-maki** [comment]
Waiting for OpenAI to add functionality
