### ISSUE TITLE
Where does the API Key go?

### ISSUE THREAD

**Issue by southbayjay** [natto-maki/ComfyUI-NegiTools#12]
Hello! 
Forgive my ignorance but where do I put the Open AI api key?? I'm very new to comfyUI and running it on Ubuntu Linux. 
Thank you!
Jason

**Comment by natto-maki** [comment]
You can pass the API key as an environment variable if you are running on Linux. For example, in the case that you are running ComfyUI from main.py, you can specify the API key as follows.

```
OPENAI_API_KEY=sk-..... python main.py
```
